In [1]:
import numpy as np

#Creation of array

In [2]:
arr = np.array([23,45,67,89,65])

In [3]:
print(arr)

[23 45 67 89 65]


In [8]:
type(arr) #nd - n dimentinal array

numpy.ndarray

In [5]:
arr

array([23, 45, 67, 89, 65])

In [6]:
arr = np.array([23,45,67,89,65,50.99])

In [7]:
arr

array([23.  , 45.  , 67.  , 89.  , 65.  , 50.99])

In [11]:
arr1 = np.array([23,45,67,89,65,50.99,'Pune'])

In [12]:
arr1

array(['23', '45', '67', '89', '65', '50.99', 'Pune'], dtype='<U32')

In [13]:
arr1[2]

'67'

In [14]:
%%timeit
arr1 = np.array([23,45,67,89,65,50.99,'Pune'])

1.43 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
arr.ndim # to cheak dimetion of array 

1

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
np.arange(2,4.5,2)

array([2., 4.])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#Two Diementional Array

In [24]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [25]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
arr2.shape

(4, 3)

In [27]:
arr2.size

12

In [28]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
arr2.ndim

2

In [30]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arr2.shape

(4, 3)

In [32]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
arr2.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [37]:
arr2.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#Three Diementional Array

In [38]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [39]:
arr2.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [40]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
arr[1:4]

array(['45', '67', '89'], dtype='<U32')

In [43]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [45]:
arr2[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#arr2[0:3,:] OR
arr2[0:3,0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr = np.array([1,2,3,1,4,2,6,2,2])

In [50]:
np.unique(arr)

array([1, 2, 3, 4, 6])

In [52]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
np.linalg.inv(arr3) # used to linear algebra

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [56]:
arr2@arr3 # cross product of matrix

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])